import { Activity, CheckCircle2, CircleDashed, Database, ServerCog } from "lucide-react";
import type { Metadata } from "next";

import { RunAnalysisButton } from "@/components/features/run-analysis-button";
import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiFetch } from "@/lib/api";
import { compactTime } from "@/lib/utils";

export const metadata: Metadata = { title: "System Status" };
export const dynamic = "force-dynamic";

type SystemStatus = { database: { status: string; events: number }; scheduler: { status: string }; model_engine: { status: string; version: string | null }; providers: Array<{ name: string; status: string; last_success: string | null; last_error: string | null; latency_ms: number | null; rate_limit_remaining: number | null; last_response_at: string | null }>; last_analysis: null | { id: string; status: string; started_at: string | null; finished_at: string | null; events_processed: number; predictions_created: number; value_picks_created: number; errors: Array<Record<string, string>>; summary: string | null } };

export default async function SystemPage() {
  const data = await apiFetch<SystemStatus>("/system/status");
  return <div className="space-y-6"><PageHeader eyebrow="Operations" title="Data sources and model status" description="Provider freshness, latency, rate limits and analysis runs are observable. Existing snapshots remain intact when a provider fails." /><section className="grid gap-3 sm:grid-cols-3"><StatusCard label="Database" status={data.database.status} detail={`${data.database.events} normalized events`} icon={Database} /><StatusCard label="Scheduler" status={data.scheduler.status} detail="Cloud jobs run in a separate worker" icon={Activity} /><StatusCard label="Model engine" status={data.model_engine.status} detail={data.model_engine.version ?? "No validated model"} icon={ServerCog} /></section><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Provider health</CardTitle><p className="mt-1 text-xs text-slate-600">Secrets are server-side and never returned here</p></div><CircleDashed className="h-4 w-4 text-slate-600" /></CardHeader><CardContent><div className="divide-y divide-border">{data.providers.map((provider) => <div key={provider.name} className="grid gap-3 py-4 md:grid-cols-[1fr_130px_160px_100px]"><div><p className="text-xs font-medium text-slate-200">{provider.name}</p><p className="mt-1 max-w-xl truncate text-[10px] text-slate-600">{provider.last_error ?? `Last success ${compactTime(provider.last_success)}`}</p></div><div><HealthBadge status={provider.status} /></div><p className="number text-[10px] text-slate-500">Response {provider.latency_ms ? `${provider.latency_ms} ms` : "—"}</p><p className="number text-[10px] text-slate-500">Quota {provider.rate_limit_remaining ?? "—"}</p></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Analysis control</CardTitle><p className="text-xs text-slate-600">Concurrent runs are rejected. Missing provider keys fail visibly without replacing stored records.</p></CardHeader><CardContent className="space-y-5"><RunAnalysisButton />{data.last_analysis && <div className="grid gap-3 rounded-lg border border-border bg-slate-950/35 p-4 sm:grid-cols-4"><RunStat label="Status" value={data.last_analysis.status} /><RunStat label="Events" value={String(data.last_analysis.events_processed)} /><RunStat label="Predictions" value={String(data.last_analysis.predictions_created)} /><RunStat label="Value picks" value={String(data.last_analysis.value_picks_created)} /><p className="col-span-full text-[10px] leading-relaxed text-slate-600">{data.last_analysis.summary}</p></div>}</CardContent></Card></div>;
}

function StatusCard({ label, status, detail, icon: Icon }: { label: string; status: string; detail: string; icon: typeof Database }) { return <Card><CardContent className="flex items-center gap-4 p-5"><div className="grid h-10 w-10 place-items-center rounded-lg bg-emerald-400/10"><Icon className="h-4 w-4 text-emerald-300" /></div><div><p className="text-[9px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-sm font-semibold text-slate-200">{status}</p><p className="mt-1 text-[10px] text-slate-600">{detail}</p></div></CardContent></Card>; }
function HealthBadge({ status }: { status: string }) { const healthy = ["ONLINE", "HEALTHY", "ACTIVE", "READY"].includes(status); return <Badge variant={healthy ? "default" : status === "DEGRADED" ? "warning" : "neutral"}>{healthy && <CheckCircle2 className="mr-1 h-3 w-3" />}{status.replace("_", " ")}</Badge>; }
function RunStat({ label, value }: { label: string; value: string }) { return <div><p className="text-[9px] uppercase tracking-wider text-slate-600">{label}</p><p className="number mt-1 text-xs text-slate-300">{value}</p></div>; }
